spring:
  datasource:
    url: jdbc:h2:tcp://localhost/file:D:/Tool/h2_db/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #이미 있으면 drop하고 create함
    properties:
      hibernate:
#        show_sql: true #System.out으로 찍어줌
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #logger로 찍어줌
    org.hibernate.type: trace