spring:
  datasource:
    url: jdbc:h2:tcp://localhost/file:D:/Tool/h2_db/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #이미 있으면 drop하고 create함
    properties:
      hibernate:
#        show_sql: true #System.out으로 찍어줌
        format_sql: true
        default_batch_fetch_size: 100 #in 쿼리로 한번에 100개씩 가져옴(pk기반으로 in 절을 날리는것이기때문에 빠르다)

logging:
  level:
    org.hibernate.SQL: debug #logger로 찍어줌
    org.hibernate.type: trace